// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var App = require("./components/App.bs.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");

((require('./index.css')));

ReactDOMRe.renderToElementWithId(React.createElement(App.make, { }), "app");

/*  Not a pure module */
